### ISSUE TITLE
Integration OncoKB annotation in Genome Nexus

### ISSUE THREAD

**Issue by onursumer** [genome-nexus/genome-nexus#17]
- model oncokb annotation in GN.
  - we can use the data from the [oncokb search endpoint](http://oncokb.org/api/v1/swagger-ui.html#!/Search/searchPostUsingPOST) directly
  - later we can switch to [the new end points](https://github.com/oncokb/oncokb/issues/1390). (or should we prioritize the new endpoint? I don't think the output format will change a lot)
- cache all oncokb genes including their curated isoforms (get file from OncoKB and store it somewhere in Genome Nexus)
- develop endpoints to annotate variants with oncokb annotation
  - maybe we can borrow [this](https://github.com/oncokb/oncokb/issues/1390) and then we don't have to do it in oncokb?
  - cache results
  - note: we should look up for the gene in the oncokb gene cache above and only send variants in genes annotated in oncokb
- implement ways to sync/clear cache
  - to start, we could manually clear cache for every oncokb release
  - ideally, oncokb can have a timestamp for every curated gene and when there is a new release we clear only the updated genes

_Copied from original issue: cBioPortal/cbioportal#1815_

TODO:
- [x] use OncoKB model directly from the API
- [x] include API generating code as module in `genome-nexus/genome-nexus` (copy from genome-nexus-java-api-client). (wait for OncoKB?)
- [x] get code reviewed and merge to master

**Comment by jjgao** [comment]
@onursumer @inodb @zhx828 : I have updated this issue. I am thinking of prioritizing this one (I know I have been back and forth a few times!), since oncokb seems to be a bottleneck in cbioportal (https://github.com/cBioPortal/cbioportal/issues/5167). Caching it per variant in genome nexus may be a good way to handle that. We will also be able to support more analysis, such as oncokb analysis in study view page.

**Comment by jjgao** [comment]
Let's discuss soon.

**Comment by jjgao** [comment]
We are considering adding oncokb data into cbioportal database directly (https://github.com/cBioPortal/cbioportal/issues/5213).
