### ISSUE TITLE
 variant search functionality

### ISSUE THREAD

**Issue by jjgao** [genome-nexus/genome-nexus#312]
as part of the new website #310 and once we have variant page #311.

[VEP variant recoder] can be used to translate variants: http://rest.ensembl.org/documentation/info/variant_recoder

e.g. http://rest.ensembl.org/variant_recoder/human/ENSP00000493543.1:p.Val600Arg?content-type=application/json

Steps to complete search:

- [ ] Frontend
  - [x] Design dropdown for search using variant recoder (handle errors)
  - [x] Implement search on frontend
      - [x] support hgvsg, hgvsp, hgvsc, dbSNP rsid
  - [x] Add a simple validator
  - [x] Only keep hgvsg starts with "NC_"
  - [x] Do not clear input in the search box when loss focus
  - [x] Support `Gene ProteinChange` e.g. BRAF V600E
  - [x] Add examples on home page

https://github.com/genome-nexus/genome-nexus-frontend/pull/88#issuecomment-892036255

- [x] It would be nice to show some more info in the dropdown e.g. "BRCA1 Protein Change"
    
    ![Screen Shot 2021-08-03 at 1 27 21 PM](https://user-images.githubusercontent.com/1334004/128059545-e6778958-b43b-4107-ac4a-5614a81d15e2.png)

    Could e.g. add Hugo Symbol, Variant Classification, Protein Change, cDNA

- [ ] (Skip) When you search by cDNA or protein change it would be good to link directly to the transcript, so we see the matching cdna/protein change at the top of the page e.g. https://deploy-preview-88--genome-nexus-frontend.netlify.app/variant/17:g.41223015_41223016del?transcriptId=ENST00000478531

- [x] The examples don't explicitly mention what they are e.g. TERT Promoter. It would be nice to settle on some styling where we can add some more examples with explanation of what they are. There is still quite some space on the page. Could e.g. do some "expand examples button". Another option would be to add some link with "more examples" and just link to a new page in the docs with more examples (https://docs.genomenexus.org/). E.g. we could create some User Guide section. (Ino)

- [x] Occasionally the search seems to hang. I'm not sure if it's b/c of calling the API to often or something else. Try e.g. `BRCA1 c.68_69del`. It has some strange behavior where occasionally it'll pop up immediately and sometimes it'll take a really long time to load. (maybe ok to wait with this one until we have gn search endpoint)

- [x] All examples are hidden when one types a gene name:

    ![Screen Shot 2021-08-03 at 1 35 16 PM](https://user-images.githubusercontent.com/1334004/128060621-95afe555-d73c-48ca-afe4-4d8857b6ac7c.png)
    
     Maybe we can guide the user a bit more here. The text could e.g. say "Variant not found. See supported formats here". Alternatively the examples could be placed lower so the search bar dropdown doesn't overlap them

- [x] Add EGFR T790M example back
- [ ] Update genome nexus document

Later we can add the backend changes to support search in geme nexus: 

- [ ] Develop new API endpoint for search
  - [ ] Research search api implementations #432
  - [ ] Think about design choices. Should we allow querying a region as well or should it be a separate endpoint?
  - [ ] Implement endpoint in backend
- [ ] Support grch38

**Comment by leexgh** [comment]
BRAF V600E: https://grch37.rest.ensembl.org/variant_recoder/human/BRAF:p.V600E?content-type=application/json
https://www.genomenexus.org/annotation/13%3Ag.140453136A%3ET?fields=hotspots

**Comment by leexgh** [comment]
How about adding an info icon next to search box?

![image.png](https://images.zenhubusercontent.com/5c3d07e393edf60c14e388c8/a6471246-9ad6-4fb8-ba1c-69a87c29d588)
